Dev
dmitrygorban/go_todo-app pull request #11
Opened 2024-04-12 16:46 UTC by dmitrygorban

2024-04-13 13:45 UTC, dirtymew requested changes
Привет Дмитрий

отличная работа - супер что создал структуру проекта, разнес сущности итд

Но есть конечно что улучшить

Давай начнем со структуры 
- посмотри на https://github.com/golang-standards/project-layout
не обязательно следовать но думаю тебя наведет на правильные мысли
- слишком сильно детализировал по файлам - нужно переделать, например у нас хранилище задач называется tasks/storage.go и там все что нужно для работы с бд получение и запись задач подключение итд в одном файле
- название файлов - нужно называть единообразно и как принято в go - те использовать _ а не -

Дальше будем уже углубляться - если сразу все править можем запутаться и слишком растянется процесс

2024-04-15 14:31 UTC, dmitrygorban commented on database/database.go
> +package database
переименовал в storage

2024-04-15 14:31 UTC, dmitrygorban commented on database/delete-task.go
> +package database
объединил всю логику в storage/storage.go

2024-04-15 14:32 UTC, dmitrygorban commented on cmd/main.go
> +	http.HandleFunc("/api/signin", handlers.SignInHandler)
вынес в server/server.go и создал отдельную структуру Server

2024-04-15 14:32 UTC, dmitrygorban commented on .gitignore
> +.DS_Store
казалось, что итак это все убрал. Тем не менее, перепроверил еще раз

2024-04-15 14:33 UTC, dmitrygorban commented on cmd/main.go
> +	install := database.DoesDbInstallRequired(dbPath)
поменял местами

2024-04-15 14:34 UTC, dmitrygorban commented on Dockerfile
> +COPY todo-app ./
в тз было сказано собрать бинарник заранее и его копировать в докерфайле.

2024-04-15 16:12 UTC, dirtymew requested changes
Привет Дмитрий

со строрадж в целом ок - немного осталось

теперь нужно в handlers и scheduler причесать...

2024-04-16 18:42 UTC, dmitrygorban commented
> * слишком сильно детализировал по файлам - нужно переделать, например у нас хранилище задач называется tasks/storage.go и там все что нужно для работы с бд получение и запись задач подключение итд в одном файле

Но я запутался в этом. Одни источники пишут, что лучше как можно мельче все дробить, так как это улучшает читаемость, другие - что наоборот. На мой вкус гораздо проще читать файлы, когда в них не очень много кода, строк по 50, максимум. 

Как лучше на ваш взгляд и почему?

2024-04-17 09:12 UTC, dirtymew requested changes
Привет Дмитрий

Дал комментарии, основной момент - у меня валяться тесты, проверь пожалуйста в чем дело и добавь в readme пример запуска тестов

2024-04-17 21:47 UTC, dirtymew approved these changes
Привет Дмитрий

не плохо получилось - работу заcчитываю. Поздравляю.

Совершенству нет предела - но хотел бы обратить внимание на оформление кода, названию переменных и функций.  Удачи

2024-04-18 09:55 UTC, merged